---
 
  - hosts: webservers
    become: yes
    tasks:
      - name: updload appication file
        copy:
          src: ../index.php
          dest: /var/www/html
          mode: 0777

      - name: configure phpini file
        lineinfile: 
          path: /etc/php.ini
          regexp: ^short_open_tag 
          line: 'short_open_tag=On'

      - name: srverice apache
        service: name=httpd state=restarted 

